import:
  - '@cspell/dict-typescript/cspell-ext.json'
  - '@cspell/dict-node/cspell-ext.json'
  - '@cspell/dict-companies/cspell-ext.json'
  - '@cspell/dict-css/cspell-ext.json'
  - '@cspell/dict-en_us/cspell-ext.json'
  - '@cspell/dict-html/cspell-ext.json'
  - '@cspell/dict-npm/cspell-ext.json'
  - '@cspell/dict-fonts/cspell-ext.json'
ignorePaths:
  - '**/node_modules'
  - '**/package.{json,json5,yaml,yml}'
  - .devenv
  - .direnv
  - npins
  - .vscode
  - .git
  - pnpm-lock*
  - .gitignore
  - '**/*.code-profile'
  - '**/dist'
  - '**/pnpm-lock.yaml'
  - '**/*.svg'
  - .npmrc
  - .cache
  - patches
  - tsconfig.json
  - '**/*.nix'
words:
  - cachix
  - corepack
  - couldn
  - Customizer
  - Datas
  - dedupe
  - devenv
  - direnv
  - envrc
  - esbuild
  - freelist
  - ianvs
  - iconify
  - Incase
  - lmdb
  - logomark
  - menuopen
  - menusection
  - modulars
  - msgpackr
  - Neue
  - nixhub
  - nixos
  - nixpkgs
  - nlewo
  - noveler
  - npins
  - optimise
  - perfectscrollbar
  - pkgs
  - popout
  - procfile
  - rrbutani
  - Segoe
  - shfmt
  - sneat
  - stylis
  - substituters
  - tabler
  - thenables
  - toolpad
  - tseslint
  - twotone
  - unplugin
  - unrs
  - Zerozawa
  - novelsaga
cache:
  cacheFormat: legacy
  cacheStrategy: metadata
  useCache: true
  cacheLocation: .cache/cspell
enabled: true
files:
  - '**/*'
